 <%= ENV["RACK_ENV"] %>:
  license_key: <%= ENV["NEW_RELIC_LICENSE_KEY"] %>
  app_name: Paris Station
  monitor_mode: true
  developer_mode: true
  log_level: error
  capture_params: true

  error_collector:
    enabled: true
    ignore_errors: "ActionController::RoutingError,Sinatra::NotFound"